# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: check_info.proto

import sys
_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='check_info.proto',
    package='paddle_hub_check_info',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x10\x63heck_info.proto\x12\x15paddle_hub_check_info\"\x80\x01\n\x08\x46ileInfo\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12.\n\x04type\x18\x02 \x01(\x0e\x32 .paddle_hub_check_info.FILE_TYPE\x12\x0f\n\x07is_need\x18\x03 \x01(\x08\x12\x0b\n\x03md5\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\"\x8b\x01\n\tCheckInfo\x12\x16\n\x0epaddle_version\x18\x01 \x01(\t\x12\x13\n\x0bhub_version\x18\x02 \x01(\t\x12\x1c\n\x14module_proto_version\x18\x03 \x01(\t\x12\x33\n\nfile_infos\x18\x04 \x03(\x0b\x32\x1f.paddle_hub_check_info.FileInfo*\x1e\n\tFILE_TYPE\x12\x08\n\x04\x46ILE\x10\x00\x12\x07\n\x03\x44IR\x10\x01\x42\x02H\x03\x62\x06proto3'
    ))
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_FILE_TYPE = _descriptor.EnumDescriptor(
    name='FILE_TYPE',
    full_name='paddle_hub_check_info.FILE_TYPE',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='FILE', index=0, number=0, options=None, type=None),
        _descriptor.EnumValueDescriptor(
            name='DIR', index=1, number=1, options=None, type=None),
    ],
    containing_type=None,
    options=None,
    serialized_start=316,
    serialized_end=346,
)
_sym_db.RegisterEnumDescriptor(_FILE_TYPE)

FILE_TYPE = enum_type_wrapper.EnumTypeWrapper(_FILE_TYPE)
FILE = 0
DIR = 1

_FILEINFO = _descriptor.Descriptor(
    name='FileInfo',
    full_name='paddle_hub_check_info.FileInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='file_name',
            full_name='paddle_hub_check_info.FileInfo.file_name',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='type',
            full_name='paddle_hub_check_info.FileInfo.type',
            index=1,
            number=2,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='is_need',
            full_name='paddle_hub_check_info.FileInfo.is_need',
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='md5',
            full_name='paddle_hub_check_info.FileInfo.md5',
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='description',
            full_name='paddle_hub_check_info.FileInfo.description',
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=44,
    serialized_end=172,
)

_CHECKINFO = _descriptor.Descriptor(
    name='CheckInfo',
    full_name='paddle_hub_check_info.CheckInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='paddle_version',
            full_name='paddle_hub_check_info.CheckInfo.paddle_version',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='hub_version',
            full_name='paddle_hub_check_info.CheckInfo.hub_version',
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='module_proto_version',
            full_name='paddle_hub_check_info.CheckInfo.module_proto_version',
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='file_infos',
            full_name='paddle_hub_check_info.CheckInfo.file_infos',
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=175,
    serialized_end=314,
)

_FILEINFO.fields_by_name['type'].enum_type = _FILE_TYPE
_CHECKINFO.fields_by_name['file_infos'].message_type = _FILEINFO
DESCRIPTOR.message_types_by_name['FileInfo'] = _FILEINFO
DESCRIPTOR.message_types_by_name['CheckInfo'] = _CHECKINFO
DESCRIPTOR.enum_types_by_name['FILE_TYPE'] = _FILE_TYPE

FileInfo = _reflection.GeneratedProtocolMessageType(
    'FileInfo',
    (_message.Message, ),
    dict(
        DESCRIPTOR=_FILEINFO,
        __module__='check_info_pb2'
        # @@protoc_insertion_point(class_scope:paddle_hub_check_info.FileInfo)
    ))
_sym_db.RegisterMessage(FileInfo)

CheckInfo = _reflection.GeneratedProtocolMessageType(
    'CheckInfo',
    (_message.Message, ),
    dict(
        DESCRIPTOR=_CHECKINFO,
        __module__='check_info_pb2'
        # @@protoc_insertion_point(class_scope:paddle_hub_check_info.CheckInfo)
    ))
_sym_db.RegisterMessage(CheckInfo)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(),
                                                _b('H\003'))
# @@protoc_insertion_point(module_scope)
