base_config:
  - usr/configs/popcs_ds_beta6.yaml
  - usr/configs/midi/cascade/opencs/opencpop_statis.yaml

binarizer_cls: data_gen.singing.binarize.OpencpopBinarizer
binary_data_dir: 'data/binary/opencpop-midi-dp'

#switch_midi2f0_step: 174000
use_midi: true  #  for midi exp
use_gt_dur: false  # for further midi exp
lambda_ph_dur: 1.0
lambda_sent_dur: 1.0
lambda_word_dur: 1.0
predictor_grad: 0.1
dur_predictor_layers: 5  # *


fs2_ckpt: ''  #
#num_valid_plots: 0
task_cls: usr.diffsinger_task.DiffSingerMIDITask

# for diffusion schedule
timesteps: 1000
K_step: 1000
max_beta: 0.02
max_tokens: 36000
max_updates: 320000
gaussian_start: True
pndm_speedup: 40

use_pitch_embed: false
use_gt_f0: false  #  for midi exp

lambda_f0: 0.
lambda_uv: 0.
dilation_cycle_length: 4  # *
rel_pos: true
predictor_layers: 5
pe_enable: true
pe_ckpt: 'checkpoints/0102_xiaoma_pe'
