MODEL:
    name: "TSN"
    format: "mp4"
    num_classes: 400
    seg_num: 3
    seglen: 1
    image_mean: [0.485, 0.456, 0.406]
    image_std: [0.229, 0.224, 0.225]
    num_layers: 50
    topk: 5

INFER:
    seg_num: 300
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 1
    kinetics_labels: "./data/kinetics_labels.json"
    filelist: "./data/tsn.list"
    video_path: "./data/mp4/1.mp4"
    single_file: True
