# https://yaml.org/type/float.html
data:
  train_manifest: data/manifest.train
  dev_manifest: data/manifest.dev-clean
  test_manifest: data/manifest.test-clean
  min_input_len: 0.0
  max_input_len: 30.0 # second
  min_output_len: 0.0
  max_output_len: .inf
  min_output_input_ratio: 0.00
  max_output_input_ratio: .inf

collator:
  batch_size: 20
  mean_std_filepath: data/mean_std.json
  unit_type: char
  vocab_filepath: data/vocab.txt
  augmentation_config: conf/augmentation.json
  random_seed: 0
  spm_model_prefix:
  spectrum_type: linear
  target_sample_rate: 16000
  max_freq: None
  n_fft: None
  stride_ms: 10.0
  window_ms: 20.0
  delta_delta: False
  dither: 1.0
  use_dB_normalization: True
  target_dB: -20
  random_seed: 0
  keep_transcription_text: False
  sortagrad: True
  shuffle_method: batch_shuffle
  num_workers: 2

model:
  num_conv_layers: 2
  num_rnn_layers: 3
  rnn_layer_size: 2048
  use_gru: False
  share_rnn_weights: True
  blank_id: 0
  ctc_grad_norm_type: instance

training:
  n_epoch: 50
  accum_grad: 1
  lr: 1e-3
  lr_decay: 0.83
  weight_decay: 1e-06
  global_grad_clip: 5.0
  log_interval: 100
  checkpoint:
    kbest_n: 50
    latest_n: 5

decoding:
  batch_size: 128
  error_rate_type: wer
  decoding_method: ctc_beam_search
  lang_model_path: data/lm/common_crawl_00.prune01111.trie.klm
  alpha: 1.9
  beta: 0.3
  beam_size: 500
  cutoff_prob: 1.0
  cutoff_top_n: 40
  num_proc_bsearch: 8
