base_config:
  - usr/configs/popcs_ds_beta6.yaml
  - usr/configs/midi/cascade/opencs/opencpop_statis.yaml

binarizer_cls: data_gen.singing.binarize.OpencpopBinarizer
binary_data_dir: 'data/binary/opencpop-midi-dp'

#switch_midi2f0_step: 174000
use_midi: true  #  for midi exp
use_gt_f0: false  #  for midi exp
use_gt_dur: false  # for further midi exp
lambda_f0: 1.0
lambda_uv: 1.0
#lambda_energy: 0.1
lambda_ph_dur: 1.0
lambda_sent_dur: 1.0
lambda_word_dur: 1.0
predictor_grad: 0.1
pe_enable: false
pe_ckpt: ''

fs2_ckpt: 'checkpoints/0302_opencpop_fs_midi/model_ckpt_steps_160000.ckpt'  #
#num_valid_plots: 0
task_cls: usr.diffsinger_task.DiffSingerMIDITask

K_step: 60
max_tokens: 40000
predictor_layers: 5
dilation_cycle_length: 4  # *
rel_pos: true
dur_predictor_layers: 5  # *
max_updates: 160000
gaussian_start: false
