name: chinese_text_detection_db_mobile
dir: "modules/image/text_recognition/chinese_text_detection_db_server"
exclude:
  - README.md

resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/image/ocr/ch_det_r50_vd_db.tar.gz
    dest: .
    uncompress: True
