name: chinese_ocr_db_crnn_mobile
dir: "modules/image/text_recognition/chinese_ocr_db_crnn_server"
exclude:
  - README.md

resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/image/ocr/chinese_ocr_db_crnn_server_assets.tar.gz
    dest: .
    uncompress: True
