name: efficientnetb6_imagenet
dir: "modules/image/classification/efficientnetb6_imagenet"
exclude:
  - README.md
resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/image/classification/efficientnetb6_imagenet_infer_model.tar.gz
    dest: .
    uncompress: True
