name: ernie_gen_couplet
dir: "modules/text/text_generation/ernie_gen_couplet"
exclude:
  - README.md
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/ernie_gen_couplet/assets.tar.gz
    dest: assets
    uncompress: True
