name: ernie_tiny_couplet
dir: "modules/text/text_generation/ernie_tiny_couplet"
exclude:
  - README.md
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/ernie_tiny_couplet/assets.tar.gz
    dest: assets
    uncompress: True
