name: ernie_skep_sentiment_analysis
dir: "modules/text/sentiment_analysis/ernie_skep_sentiment_analysis"
exclude:
  - README.md
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/ernie_skep_sentiment_analysis/assets.tar.gz
    dest: assets
    uncompress: True
