name: ernie_gen_lover_words
dir: "modules/text/text_generation/ernie_gen_lover_words"
exclude:
  - README.md
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/ernie_gen_lover_words/assets.tar.gz
    dest: assets
    uncompress: True
