name: human_pose_estimation_hrnet_w18_samll_v1_humanseg
dir: "modules/image/semantic_segmentation/hrnet_w18_samll_v1_humanseg"
exclude:
    - README.md
resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/image/semantic_segmentation/humanseg_mobile_inference.tar.gz
    dest: .
    uncompress: True
