name: lda_novel
dir: "modules/text/semantic_model/lda_novel"
exclude:

resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/nlp/semantic_model/lda_novel.tar.gz
    dest: .
    uncompress: True
