name: resnet18_vd_imagenet
dir: "modules/image/classification/resnet18_vd_imagenet"
exclude:
  - README.md
resources:
  -
    url: https://bj.bcebos.com/paddlehub/hub_dev/resnet18_vd_imagenet_model.tar.gz
    dest: .
    uncompress: True
