name: senta_cnn
dir: "modules/text/sentiment_analysis/senta_cnn"
exclude:
  - README.md
  - test.py
resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/nlp/sentiment_analysis/senta_cnn_assets.tar.gz
    dest: .
    uncompress: True
