name: senta_lstm
dir: "modules/text/sentiment_analysis/senta_lstm"
exclude:
  - README.md
  - test.py
resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/nlp/sentiment_analysis/senta_lstm_assets.tar.gz
    dest: .
    uncompress: True
