name: senta_bilstm
dir: "modules/text/sentiment_analysis/senta_bilstm"
exclude:
  - README.md
  - test.py
resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/nlp/sentiment_analysis/senta_bilstm_assets.tar.gz
    dest: .
    uncompress: True
