name: human_pose_estimation_shufflenet_humanseg
dir: "modules/image/semantic_segmentation/shufflenet_humanseg"
exclude:
    - README.md
resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/image/semantic_segmentation/humanseg_lite_inference.tar.gz
    dest: .
    uncompress: True
