name: slda_weibo
dir: "modules/text/semantic_model/slda_weibo"
exclude:

resources:
  -
    url: https://bj.bcebos.com/paddlehub/model/nlp/semantic_model/slda_weibo.tar.gz
    dest: .
    uncompress: True
