name: VideoTag_TSN_AttentionLSTM
dir: "modules/video/classification/VideoTag_TSN_AttentionLSTM"
exclude:
  - README.md
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/video/video_classifcation/videotag_tsn_lstm.tar.gz
    dest: weights
    uncompress: True
