base_config:
  - configs/tts/lj/fs2.yaml

max_frames: 8000
audio_sample_rate: 24000
hop_size: 128            # Hop size.
fft_size: 512           # FFT size.
win_size: 512           # FFT size.
fmin: 30
fmax: 12000
min_level_db: -120

binary_data_dir: 'xxx'

pitch_type: frame
task_cls: tasks.tts.pe.PitchExtractionTask
pitch_extractor_conv_layers: 2


# config for experiments
max_tokens: 20000
use_spk_embed: false
num_valid_plots: 10
max_updates: 60000
