SSDOutputDecoder:
  background_label: 0
  keep_top_k: 200
  nms_eta: 1.0
  nms_threshold: 0.45
  nms_top_k: 400
  score_threshold: 0.01

MultiBoxHead:
  base_size: 300
  aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2.], [2.]]
  min_ratio: 15
  max_ratio: 90
  min_sizes: [30.0, 60.0, 111.0, 162.0, 213.0, 264.0]
  max_sizes: [60.0, 111.0, 162.0, 213.0, 264.0, 315.0]
  steps: [8, 16, 32, 64, 100, 300]
  offset: 0.5
  flip: true
  kernel_size: 3
  pad: 1
