base_config:
  - ./popcs_ds_beta6.yaml

fs2_ckpt: checkpoints/popcs_fs2_pmf0_1230/model_ckpt_steps_160000.ckpt  # to be infer
num_valid_plots: 0
task_cls: usr.diffsinger_task.DiffSingerOfflineTask

# tmp:
#pe_enable: true
#pe_ckpt: ''
vocoder: vocoders.hifigan.HifiGAN
vocoder_ckpt: checkpoints/0109_hifigan_bigpopcs_hop128
