base_config:
  - configs/singing/fs2.yaml

audio_sample_rate: 24000
hop_size: 128            # Hop size.
fft_size: 512           # FFT size.
win_size: 512           # FFT size.
fmin: 30
fmax: 12000
min_level_db: -120

binarization_args:
  with_wav: true
  with_spk_embed: false
  with_align: true
raw_data_dir: 'data/raw/popcs'
processed_data_dir: 'data/processed/popcs'
binary_data_dir: 'data/binary/popcs-pmf0'
num_spk: 1
datasets: [
  'popcs',
]
test_prefixes: [
  'popcs-说散就散',
  'popcs-隐形的翅膀',
]

task_cls: tasks.tts.fs2.FastSpeech2Task
#vocoder: usr.singingvocoder.highgan.HighGAN
#vocoder_ckpt: checkpoints/h_2_model/checkpoint-530000steps.pkl
vocoder: vocoders.hifigan.HifiGAN
vocoder_ckpt: checkpoints/0109_hifigan_bigpopcs_hop128
use_nsf: true

# config for experiments
max_tokens: 18000
use_spk_embed: false
num_valid_plots: 10
max_updates: 160000
save_gt: true

# tmp:
#pe_enable: true
#pe_ckpt: ''
